### ISSUE TITLE
Complains about a valid SSH config property

### ISSUE THREAD

**Issue by farzadmf** [Julien-R44/fast-ssh#12]
Hi, first of all, thank you for the tool, looks very good

One issue I have is that it's complaining about the `PubkeyAcceptedKeyTypes` property I've set for a server in my SSH config file. This is a valid property in SSH config, so I think even if the tool doesn't use that property, it's good to not error out

Thank you

**Comment by Julien-R44** [comment]
Thanks you very much !
I was not aware of this property, it was not even in [the man page of ssh_config](https://linux.die.net/man/5/ssh_config)! I'll fix it asap, thanks for reporting the error

**Comment by farzadmf** [comment]
Oh wow, interesting that it's not there. TBH, I didn't know about the property either, but recently, when trying to connect to CircleCI, it was failing, so I had to tell the connection to use a less-secure algorithm :open_mouth: and that's how I have it in my config :slightly_smiling_face:

**Comment by Julien-R44** [comment]
I just upgraded dependecy to ssh_cfg that handles now all sshd options including `PubkeyAcceptedKeyTypes` ( https://github.com/azriel91/ssh_cfg/pull/2 ) in release v0.3.1 👍

**Comment by farzadmf** [comment]
Hey @Julien-R44 , great to hear, however, I think I'm still getting the error, and from what I see, I am using `0.3.1` :thinking:

**Comment by Julien-R44** [comment]
Are you sure you are using version 0.3.1? 
I added this to my SSH configuration and it works fine: 
![image](https://user-images.githubusercontent.com/8337858/144714491-295d1928-e598-4604-adfa-36f1cc5f7701.png)
