### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by hockeymikey** [Julien-R44/fast-ssh#17]
It would be nice to be able to theme it with even something as simple as different accent color.

**Comment by Julien-R44** [comment]
Hey 👋 

It is already possible, take a look here: https://github.com/Julien-R44/fast-ssh#configuration

It's pretty basic but I think it's enough ! Is it ok for you ? If not, please suggest me what you would add

**Comment by hockeymikey** [comment]
Oops, guess I missed it. It's solid, I think it's good enough for me. I'd probably still just go overboard and allow say individual theming of say an individual box color, or colorizing the highlighted group a different color. Not a huge priority I think though.

**Comment by Julien-R44** [comment]
Okay well I don't think it would be super useful to allow this, but feel free to send a PR for it ! 
Closing this for now
