### ISSUE TITLE
Custom layouts

### ISSUE THREAD

**Issue by hockeymikey** [Julien-R44/fast-ssh#18]
I think this is apart of a larger epic of multiple issues (or milestone?) that goes into this.
But basically, allow the user to define a custom layout based on common elements. I'm not sure on the file structure of this in a config file, but that is something that can be ironed out.
User should be able to define what row they start in or column. I'm not sure what the best way for this would be with a more static approach with defining the row/col or more dynamic defining just an order and size (percentage maybe?) and calculating that and where they should be. Granted I think it should allow for white space or bigger gaps between elements if a user desires.

**Comment by Julien-R44** [comment]
If I understand correctly: 
- Your first proposal is to add a configuration option that allows you to define a group to display when launching FastSSH. For that I agree, I think it can be useful !

On the other hand, the second proposal which consists in configuring the layout, I don't really get the interest. Could you explain why you think such a feature would be necessary? 

However, I think it would be quite easy to add, we already have a layout file in which the sizes of the different blocks are defined using percentages: https://github.com/Julien-R44/fast-ssh/blob/main/src/layout.rs

Would you feel like doing a PR for this?

**Comment by hockeymikey** [comment]
@Julien-R44 Why wouldn't the issue be needed? The current layout is limited and sucks. Nothing great for a deeper workflow but others have different layouts they desire so giving the freedom to the user to determine what works best for them
And no, I am much too busy for that.

**Comment by Julien-R44** [comment]
I think you can begin by being respectful and avoid terms like "sucks". 
It's not a feature I'll be using so I'm closing the issue. If you want it, make a PR.

**Comment by hockeymikey** [comment]
Lmao, respectful? Using terms like "sucks" isn't non-respectful. I think you should check your ego, respectfully, if you think any part of that was disrespectful. I will not be making a PR if all you can think about this project is me me me and not what the user may want or need. Sure I'm the one making this but its in guidance and understanding of what would make this great and other people find useful. I'll just fork this then and make it my own :)

**Comment by Julien-R44** [comment]
Of course "sucks" is rude and disrespectful. Coming up with a project you're using for free and saying "this thing sucks" is obviously disrespectful, I don't even know how you can think otherwise. Saying that "the layout is limited and could be improved" is respectful.

Fork the project and do what you want I don't give a shit lmao
