### ISSUE TITLE
fast-ssh doesn't properly handle multiple hostnames

### ISSUE THREAD

**Issue by Cpapa97** [Julien-R44/fast-ssh#2]
Host can have aliased hostnames, so with my config like this
```config
Host short_hostname long_hostname
  HostName ...
  User ...
  ...
```
The error comes back as `ssh: Could not resolve hostname short_hostname long_hostname: No such host is known.` instead of using only one of the hostnames.

This is a nice project though!

**Comment by Julien-R44** [comment]
Hey, thanks for the notice, I fixed it 👍
