### ISSUE TITLE
Panic when ~/.ssh/config does not exist

### ISSUE THREAD

**Issue by pantsman0** [Julien-R44/fast-ssh#3]
When running fast-ssh on a machine that does not have an account local ssh config, the application will crash with the following error:
`thread 'main' panicked at 'Failed to parse ~/.ssh/config: SshConfigRead { path: "C:\\Users\\[redacted]\\.ssh\\config", error: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } }', C:\Users\[redacted]\.cargo\registry\src\github.com-1ecc6299db9ec823\fast-ssh-0.1.3\src\ssh_config_store.rs:32:14`

Referenced line: `https://github.com/Julien-R44/fast-ssh/blob/419bc1b094f5cf0e6a77bd5241f48f8b43e7353c/src/ssh_config_store.rs#L32`

**Comment by Julien-R44** [comment]
Hey thanks for reporting. I'll take a look at this 👍
