### ISSUE TITLE
Feature request: fuzzy search matching for hosts

### ISSUE THREAD

**Issue by ironicbadger** [Julien-R44/fast-ssh#6]
Arrows keys are so 1999. Would be great if you could launch the app and start typing a few chars right away to match a host.

**Comment by Julien-R44** [comment]
Thank you it's a good idea ! I will add this asap

**Comment by Julien-R44** [comment]
Hey, it's implemented, you can read more about it in the README. 
I will publish a new version right away. Don't hesitate to give me your opinion ! Thanks for the idea 👍
